function b$c(){}
function yed(){}
function Ded(){}
function Ced(){}
function Ied(){}
function Ged(){}
function P3c(a,b){a.Uf(b)}
function c$c(a,b,c){XBb.call(this,a,b,c)}
function Led(){Led=HEd;Fed=new Ied}
function Hed(a){if(!a.b){a.b=true;sr();Zj(pr,cFd);wr();return true}return false}
function l4c(a){var b;!a.q&&(a.q=(b=new c$c((!a.b&&(a.b=new xu),a.b),(!a.bb&&(a.bb=new zed(new Ded)),a.bb),(!a.p&&(a.p=new h$c),a.p)),P3c(b,(!a.e&&(a.e=new mBb),a.e)),b));return a.q}
function zed(){var a,b;this.b=(Led(),a=new ve((b=new cud,b.b.b+="<h1>CSS3 Charts<\/h1> <h4> No JavaScript, no images, just pure CSS code. <span class='red_info'>Optimized for Firefox. <\/span> <br> <span class='blue_info'>Hint: try to hover over the charts! You may also reload the page to see the enter animation.<\/span> <\/h4> <br> <div class='user_outer'> <div class='bar_chart w30'> <span class='scale h10'>10 -<\/span> <span class='scale h20'>20 -<\/span> <span class='scale h30'>30 -<\/span> <span class='scale h40'>40 -<\/span> <span class='scale h50'>50 -<\/span> <span class='scale h60'>60 -<\/span> <span class='scale h70'>70 -<\/span> <span class='scale h80'>80 -<\/span> <span class='scale h90'>90 - <\/span> <span class='scale h100'>100 -<\/span> <div class='legend'> <span class='square turquoise'><\/span> winter <br> <span class='square blue_light'><\/span> spring <br> <span class='square purple'><\/span> summer <br> <span class='square pink'><\/span> autumn <br> <\/div> <span class='space'><\/span> <dl> <dt>January<\/dt> <dd class='turquoise v50'> <span>50<\/span> <\/dd> <\/dl> <dl> <dt>February<\/dt> <dd class='turquoise v43'> <span>43<\/span> <\/dd> <\/dl> <dl> <dt>March<\/dt> <dd class='turquoise v57'> <span>57<\/span> <\/dd> <\/dl> <dl> <dt>April<\/dt> <dd class='blue_light v45'> <span>45<\/span> <\/dd> <\/dl> <dl> <dt>May<\/dt> <dd class='blue_light v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>June<\/dt> <dd class='blue_light v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>July<\/dt> <dd class='purple v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>August<\/dt> <dd class='purple v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>September<\/dt> <dd class='purple v25'> <span>25<\/span> <\/dd> <\/dl> <dl> <dt>October<\/dt> <dd class='pink v33'> <span>33<\/span> <\/dd> <\/dl> <dl> <dt>November<\/dt> <dd class='pink v53'> <span>53<\/span> <\/dd> <\/dl> <dl> <dt>December<\/dt> <dd class='pink v64'> <span>64<\/span> <\/dd> <\/dl> <\/div> <div class='pie_outer'> <div class='circle'> <div class='triangle summer'><\/div> <div class='triangle autumn'><\/div> <div class='triangle autumn2'><\/div> <div class='triangle winter'><\/div> <div class='triangle winter2'><\/div> <div class='triangle spring'><\/div> <div class='center'><\/div> <\/div> <span class='percent nobg purple'>18%<\/span> <span class='percent nobg pink'>30%<\/span> <span class='percent nobg turquoise'>30%<\/span> <span class='percent nobg blue_light'>22%<\/span> <div class='center_circle'><\/div> <\/div> <\/div>",new K1(b.b.b)).b),Hed(Fed),a)}
_=c$c.prototype=b$c.prototype=new HBb;_.gC=function d$c(){return YT};_.Vf=function e$c(){};_.Yf=function f$c(){MBb(this,new GFb((g_c(),f_c),this))};_.cM={37:1,105:1,106:1};_=u7c.prototype;_.nc=function y7c(){HDb(this.c,l4c(this.b.b))};_=zed.prototype=yed.prototype=new lCb;_.$f=function Aed(){return this.b};_.gC=function Bed(){return QW};_.b=null;_=Ded.prototype=Ced.prototype=new bd;_.gC=function Eed(){return PW};var Fed=null;_=Ied.prototype=Ged.prototype=new bd;_.gC=function Jed(){return OW};_.Vb=function Ked(){return cFd};_.b=false;var YT=$qd(JHd,'CSS3ChartPresenter',hJ),QW=$qd(KHd,'CSS3ChartView',oJ),PW=$qd(KHd,'CSS3ChartView_BinderImpl',YY),OW=$qd(KHd,'CSS3ChartView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',YY);bFd(Hk)(17);