function M0c(){}
function hhd(){}
function mhd(){}
function lhd(){}
function rhd(){}
function phd(){}
function y6c(a,b){a.Yf(b)}
function N0c(a,b,c){QCb.call(this,a,b,c)}
function uhd(){uhd=qHd;ohd=new rhd}
function qhd(a){if(!a.b){a.b=true;Pr();kk(Mr,NHd);Tr();return true}return false}
function W6c(a){var b;!a.q&&(a.q=(b=new N0c((!a.b&&(a.b=new Uu),a.b),(!a.bb&&(a.bb=new ihd(new mhd)),a.bb),(!a.p&&(a.p=new S0c),a.p)),y6c(b,(!a.e&&(a.e=new fCb),a.e)),b));return a.q}
function ihd(){var a,b;this.b=(uhd(),a=new ve((b=new Nwd,b.b.b+="<h1>CSS3 Charts<\/h1> <h4> No JavaScript, no images, just pure CSS code. <span class='red_info'>Optimized for Firefox. <\/span> <br> <span class='blue_info'>Hint: try to hover over the charts! You may also reload the page to see the enter animation.<\/span> <\/h4> <br> <div class='user_outer'> <div class='bar_chart w30'> <span class='scale h10'>10 -<\/span> <span class='scale h20'>20 -<\/span> <span class='scale h30'>30 -<\/span> <span class='scale h40'>40 -<\/span> <span class='scale h50'>50 -<\/span> <span class='scale h60'>60 -<\/span> <span class='scale h70'>70 -<\/span> <span class='scale h80'>80 -<\/span> <span class='scale h90'>90 - <\/span> <span class='scale h100'>100 -<\/span> <div class='legend'> <span class='square turquoise'><\/span> winter <br> <span class='square blue_light'><\/span> spring <br> <span class='square purple'><\/span> summer <br> <span class='square pink'><\/span> autumn <br> <\/div> <span class='space'><\/span> <dl> <dt>January<\/dt> <dd class='turquoise v50'> <span>50<\/span> <\/dd> <\/dl> <dl> <dt>February<\/dt> <dd class='turquoise v43'> <span>43<\/span> <\/dd> <\/dl> <dl> <dt>March<\/dt> <dd class='turquoise v57'> <span>57<\/span> <\/dd> <\/dl> <dl> <dt>April<\/dt> <dd class='blue_light v45'> <span>45<\/span> <\/dd> <\/dl> <dl> <dt>May<\/dt> <dd class='blue_light v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>June<\/dt> <dd class='blue_light v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>July<\/dt> <dd class='purple v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>August<\/dt> <dd class='purple v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>September<\/dt> <dd class='purple v25'> <span>25<\/span> <\/dd> <\/dl> <dl> <dt>October<\/dt> <dd class='pink v33'> <span>33<\/span> <\/dd> <\/dl> <dl> <dt>November<\/dt> <dd class='pink v53'> <span>53<\/span> <\/dd> <\/dl> <dl> <dt>December<\/dt> <dd class='pink v64'> <span>64<\/span> <\/dd> <\/dl> <\/div> <div class='pie_outer'> <div class='circle'> <div class='triangle summer'><\/div> <div class='triangle autumn'><\/div> <div class='triangle autumn2'><\/div> <div class='triangle winter'><\/div> <div class='triangle winter2'><\/div> <div class='triangle spring'><\/div> <div class='center'><\/div> <\/div> <span class='percent nobg purple'>18%<\/span> <span class='percent nobg pink'>30%<\/span> <span class='percent nobg turquoise'>30%<\/span> <span class='percent nobg blue_light'>22%<\/span> <div class='center_circle'><\/div> <\/div> <\/div>",new u2(b.b.b)).b),qhd(ohd),a)}
_=N0c.prototype=M0c.prototype=new ACb;_.gC=function O0c(){return FU};_.Zf=function P0c(){};_.ag=function Q0c(){FCb(this,new zGb((R1c(),Q1c),this))};_.cM={37:1,105:1,106:1};_=dad.prototype;_.rc=function had(){AEb(this.c,W6c(this.b.b))};_=ihd.prototype=hhd.prototype=new eDb;_.cg=function jhd(){return this.b};_.gC=function khd(){return xX};_.b=null;_=mhd.prototype=lhd.prototype=new bd;_.gC=function nhd(){return wX};var ohd=null;_=rhd.prototype=phd.prototype=new bd;_.gC=function shd(){return vX};_.Vb=function thd(){return NHd};_.b=false;var FU=Jtd(uKd,'CSS3ChartPresenter',HJ),xX=Jtd(vKd,'CSS3ChartView',OJ),wX=Jtd(vKd,'CSS3ChartView_BinderImpl',FZ),vX=Jtd(vKd,'CSS3ChartView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',FZ);MHd(Uk)(17);