function a5c(){}
function xld(){}
function Cld(){}
function Bld(){}
function Hld(){}
function Fld(){}
function Oad(a,b){a.bg(b)}
function b5c(a,b,c){EDb.call(this,a,b,c)}
function Kld(){Kld=GLd;Eld=new Hld}
function Gld(a){if(!a.b){a.b=true;es();lk(bs,bMd);is();return true}return false}
function kbd(a){var b;!a.q&&(a.q=(b=new b5c((!a.b&&(a.b=new jv),a.b),(!a.bb&&(a.bb=new yld(new Cld)),a.bb),(!a.p&&(a.p=new g5c),a.p)),Oad(b,(!a.e&&(a.e=new VCb),a.e)),b));return a.q}
function yld(){var a,b;this.b=(Kld(),a=new ve((b=new bBd,b.b.b+="<h1>CSS3 Charts<\/h1> <h4> No JavaScript, no images, just pure CSS code. <span class='red_info'>Optimized for Firefox. <\/span> <br> <span class='blue_info'>Hint: try to hover over the charts! You may also reload the page to see the enter animation.<\/span> <\/h4> <br> <div class='user_outer'> <div class='bar_chart w30'> <span class='scale h10'>10 -<\/span> <span class='scale h20'>20 -<\/span> <span class='scale h30'>30 -<\/span> <span class='scale h40'>40 -<\/span> <span class='scale h50'>50 -<\/span> <span class='scale h60'>60 -<\/span> <span class='scale h70'>70 -<\/span> <span class='scale h80'>80 -<\/span> <span class='scale h90'>90 - <\/span> <span class='scale h100'>100 -<\/span> <div class='legend'> <span class='square turquoise'><\/span> winter <br> <span class='square blue_light'><\/span> spring <br> <span class='square purple'><\/span> summer <br> <span class='square pink'><\/span> autumn <br> <\/div> <span class='space'><\/span> <dl> <dt>January<\/dt> <dd class='turquoise v50'> <span>50<\/span> <\/dd> <\/dl> <dl> <dt>February<\/dt> <dd class='turquoise v43'> <span>43<\/span> <\/dd> <\/dl> <dl> <dt>March<\/dt> <dd class='turquoise v57'> <span>57<\/span> <\/dd> <\/dl> <dl> <dt>April<\/dt> <dd class='blue_light v45'> <span>45<\/span> <\/dd> <\/dl> <dl> <dt>May<\/dt> <dd class='blue_light v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>June<\/dt> <dd class='blue_light v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>July<\/dt> <dd class='purple v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>August<\/dt> <dd class='purple v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>September<\/dt> <dd class='purple v25'> <span>25<\/span> <\/dd> <\/dl> <dl> <dt>October<\/dt> <dd class='pink v33'> <span>33<\/span> <\/dd> <\/dl> <dl> <dt>November<\/dt> <dd class='pink v53'> <span>53<\/span> <\/dd> <\/dl> <dl> <dt>December<\/dt> <dd class='pink v64'> <span>64<\/span> <\/dd> <\/dl> <\/div> <div class='pie_outer'> <div class='circle'> <div class='triangle summer'><\/div> <div class='triangle autumn'><\/div> <div class='triangle autumn2'><\/div> <div class='triangle winter'><\/div> <div class='triangle winter2'><\/div> <div class='triangle spring'><\/div> <div class='center'><\/div> <\/div> <span class='percent nobg purple'>18%<\/span> <span class='percent nobg pink'>30%<\/span> <span class='percent nobg turquoise'>30%<\/span> <span class='percent nobg blue_light'>22%<\/span> <div class='center_circle'><\/div> <\/div> <\/div>",new f3(b.b.b)).b),Gld(Eld),a)}
_=b5c.prototype=a5c.prototype=new oDb;_.gC=function c5c(){return qV};_.cg=function d5c(){};_.fg=function e5c(){tDb(this,new nHb((f6c(),e6c),this))};_.cM={37:1,105:1,106:1};_=ted.prototype;_.rc=function xed(){oFb(this.c,kbd(this.b.b))};_=yld.prototype=xld.prototype=new UDb;_.hg=function zld(){return this.b};_.gC=function Ald(){return iY};_.b=null;_=Cld.prototype=Bld.prototype=new bd;_.gC=function Dld(){return hY};var Eld=null;_=Hld.prototype=Fld.prototype=new bd;_.gC=function Ild(){return gY};_.Vb=function Jld(){return bMd};_.b=false;var qV=Zxd(LOd,'CSS3ChartPresenter',aK),iY=Zxd(MOd,'CSS3ChartView',hK),hY=Zxd(MOd,'CSS3ChartView_BinderImpl',q$),gY=Zxd(MOd,'CSS3ChartView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',q$);aMd(Vk)(17);