function s$c(){}
function Ped(){}
function Ued(){}
function Ted(){}
function Zed(){}
function Xed(){}
function e4c(a,b){a.Sf(b)}
function t$c(a,b,c){CCb.call(this,a,b,c)}
function afd(){afd=ZEd;Wed=new Zed}
function Yed(a){if(!a.a){a.a=true;wr();Yj(tr,uFd);Ar();return true}return false}
function C4c(a){var b;!a.p&&(a.p=(b=new t$c((!a.a&&(a.a=new Au),a.a),(!a.$&&(a.$=new Qed(new Ued)),a.$),(!a.o&&(a.o=new y$c),a.o)),e4c(b,(!a.d&&(a.d=new TBb),a.d)),b));return a.p}
function Qed(){var a,b;this.a=(afd(),a=new ue((b=new uud,Yl(b.a,"<h1>CSS3 Charts<\/h1> <h4> No JavaScript, no images, just pure CSS code. <span class='red_info'>Optimized for Firefox. <\/span> <br> <span class='blue_info'>Hint: try to hover over the charts! You may also reload the page to see the enter animation.<\/span> <\/h4> <br> <div class='user_outer'> <div class='bar_chart w30'> <span class='scale h10'>10 -<\/span> <span class='scale h20'>20 -<\/span> <span class='scale h30'>30 -<\/span> <span class='scale h40'>40 -<\/span> <span class='scale h50'>50 -<\/span> <span class='scale h60'>60 -<\/span> <span class='scale h70'>70 -<\/span> <span class='scale h80'>80 -<\/span> <span class='scale h90'>90 - <\/span> <span class='scale h100'>100 -<\/span> <div class='legend'> <span class='square turquoise'><\/span> winter <br> <span class='square blue_light'><\/span> spring <br> <span class='square purple'><\/span> summer <br> <span class='square pink'><\/span> autumn <br> <\/div> <span class='space'><\/span> <dl> <dt>January<\/dt> <dd class='turquoise v50'> <span>50<\/span> <\/dd> <\/dl> <dl> <dt>February<\/dt> <dd class='turquoise v43'> <span>43<\/span> <\/dd> <\/dl> <dl> <dt>March<\/dt> <dd class='turquoise v57'> <span>57<\/span> <\/dd> <\/dl> <dl> <dt>April<\/dt> <dd class='blue_light v45'> <span>45<\/span> <\/dd> <\/dl> <dl> <dt>May<\/dt> <dd class='blue_light v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>June<\/dt> <dd class='blue_light v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>July<\/dt> <dd class='purple v30'> <span>30<\/span> <\/dd> <\/dl> <dl> <dt>August<\/dt> <dd class='purple v35'> <span>35<\/span> <\/dd> <\/dl> <dl> <dt>September<\/dt> <dd class='purple v25'> <span>25<\/span> <\/dd> <\/dl> <dl> <dt>October<\/dt> <dd class='pink v33'> <span>33<\/span> <\/dd> <\/dl> <dl> <dt>November<\/dt> <dd class='pink v53'> <span>53<\/span> <\/dd> <\/dl> <dl> <dt>December<\/dt> <dd class='pink v64'> <span>64<\/span> <\/dd> <\/dl> <\/div> <div class='pie_outer'> <div class='circle'> <div class='triangle summer'><\/div> <div class='triangle autumn'><\/div> <div class='triangle autumn2'><\/div> <div class='triangle winter'><\/div> <div class='triangle winter2'><\/div> <div class='triangle spring'><\/div> <div class='center'><\/div> <\/div> <span class='percent nobg purple'>18%<\/span> <span class='percent nobg pink'>30%<\/span> <span class='percent nobg turquoise'>30%<\/span> <span class='percent nobg blue_light'>22%<\/span> <div class='center_circle'><\/div> <\/div> <\/div>"),new V1(bm(b.a))).a),Yed(Wed),a)}
_=t$c.prototype=s$c.prototype=new mCb;_.gC=function u$c(){return aU};_.Tf=function v$c(){};_.Wf=function w$c(){rCb(this,new lGb((x_c(),w_c),this))};_.cM={37:1,105:1,106:1};_=L7c.prototype;_.kc=function P7c(){mEb(this.b,C4c(this.a.a))};_=Qed.prototype=Ped.prototype=new SCb;_.Yf=function Red(){return this.a};_.gC=function Sed(){return UW};_.a=null;_=Ued.prototype=Ted.prototype=new bd;_.gC=function Ved(){return TW};var Wed=null;_=Zed.prototype=Xed.prototype=new bd;_.gC=function $ed(){return SW};_.Sb=function _ed(){return uFd};_.a=false;var aU=prd($Hd,'CSS3ChartPresenter',lJ),UW=prd(_Hd,'CSS3ChartView',sJ),TW=prd(_Hd,'CSS3ChartView_BinderImpl',aZ),SW=prd(_Hd,'CSS3ChartView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',aZ);tFd(Gk)(17);